/** Page titles shown in the topbar, keyed by route. */
export const TITLES: Record<string, string> = {
  dashboard: 'Dashboard',
  attendance: 'Attendance & Geo Tracking',
  shifts: 'Roster',
  timesheet: 'Timesheet',
  leave: 'Leave Management',
  expenses: 'Expenses & Reimbursements',
  approvals: 'Approvals',

  employees: 'Employee Directory',
  org: 'Org Chart',
  celebrations: 'Celebrations',
  announcements: 'Announcements',
  engagement: 'Engagement',
  assets: 'IT Assets',
  helpdesk: 'HR Helpdesk',

  payroll: 'Payroll & Payslips',
  tax: 'Tax Declaration',
  benefits: 'Benefits & Flexible Pay',

  performance: 'Performance',
  learning: 'Learning & Certifications',
  hiring: 'Internal Hiring',
  recruitment: 'Recruitment',
  users: 'User Management',
  jobtitles: 'Job Titles',
  lifecycle: 'Employee Lifecycle',
  software: 'Software Assets',
  devplans: 'Development Plans',
  events: 'Company Events',
  exports: 'Export Center',
  customreports: 'Custom Reports',
  integrations: 'Integration Settings',
  planner: 'Project Planner',
  onboarding: 'Onboarding',
  exit: 'Exit & Full-and-Final',

  clients: 'Clients & Statements of Work',
  requirements: 'Requirement Book',
  bench: 'Bench & Consultants',
  placements: 'Placements',
  billing: 'Billing & Receivables',
  vendors: 'Vendor Management',

  exec: 'Executive View',
  reports: 'Reports & Analytics',
  documents: 'Documents & Letters',
  security: 'Security & Audit',
  settings: 'Settings & Access Control',
};
